export const KEY_REDUCER = 'NCCU_COURSE';
export const INIT = `${KEY_REDUCER}/INIT`;
export const FETCH_SEMESTER_LIST = `${KEY_REDUCER}/FETCH_SEMESTER_LIST`;
export const SET_SEMESTER_LIST = `${KEY_REDUCER}/SET_SEMESTER_LIST`;
export const FETCH_COURSES_LIST = `${KEY_REDUCER}/FETCH_COURSES_LIST`;
export const SET_COURSES_LIST_MAP = `${KEY_REDUCER}/SET_COURSES_LIST_MAP`;
export const SET_SEMESTER_LIST_LOADING = `${KEY_REDUCER}/SET_SEMESTER_LIST_LOADING`;
export const SET_COURSES_LIST_LOADING = `${KEY_REDUCER}/SET_COURSES_LIST_LOADING`;

export const APP_WIDTH = 1000;
export const NAVIGATION_BAR_HEIGHT = 50;
export const APP_PADDING = 10;
export const ROW_RANGE = 50;
