export const KEY_REDUCER = 'NCCU_COURSE';
export const INIT = `${KEY_REDUCER}/INIT`;
export const FETCH_SEMESTER_LIST = `${KEY_REDUCER}/FETCH_SEMESTER_LIST`;
export const SET_SEMESTER_LIST = `${KEY_REDUCER}/SET_SEMESTER_LIST`;

export const APP_WIDTH = 1000;
export const NAVIGATION_BAR_HEIGHT = 50;
export const APP_PADDING = 10;
